apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        image: hemant9766/backendjob-website:v7
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_HOST
          value: "mysql-service"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "root"
        - name: SPRING_MAIL_HOST
          value: "smtp.gmail.com"
        - name: SPRING_MAIL_PORT
          value: "587"
        - name: SPRING_MAIL_USERNAME
          value: "acchajobs15@gmail.com"
        - name: SPRING_MAIL_PASSWORD
          value: "txnb swed pwyv esyv"
        - name: SUPERADMIN_MAIL_USERNAME
          value: "acchajobs1@gmail.com"
        - name: SUPERADMIN_MAIL_PASSWORD
          value: "mirm bolj zhkc qrqp"
